export const PATIENT_FIELD_ALIASES = {
  patientId: [
    "Patient ID",
    "PatientId",
    "Patient Number",
    "Pt ID",
    "MRN",
    "Customer ID",
    "Acct #",
  ],
  patientName: [
    "Patient Name",
    "Patient_Name",
    "PatientName",
    "Name",
    "Full Name",
    "Full_Name",
    "Patient",
    "Customer Name",
    "Customer_Name",
  ],
  firstName: [
    "First Name",
    "First_Name",
    "FirstName",
    "Patient First Name",
    "Patient_First_Name",
    "PatientFirstName",
    "FName",
  ],
  lastName: [
    "Last Name",
    "Last_Name",
    "LastName",
    "Patient Last Name",
    "Patient_Last_Name",
    "PatientLastName",
    "LName",
  ],
  dob: ["DOB", "Date of Birth", "Birth Date", "Patient DOB"],

  dateOfDeath: [
    "DOD",
    "Date Of Death",
    "Date of Death",
    "DateOfDeath",
    "Death Date",
    "Death_Date",
    "death_date",
    "date_of_death",
    "Patient DOD",
    "Patient Date Of Death",
    "Clinical DOD",
  ],

  phone: [
    "Phone",
    "Phone Number",
    "Patient Phone",
    "Home Phone",
    "Mobile Phone",
    "Cell Phone",
    "Billing Address Phone",
    "Billing Address Mobile Phone",
    "Delivery Address Phone",
  ],
  email: [
    "Email",
    "Email Address",
    "Patient Email",
    "E-Mail",
    "Billing Address Email Address",
  ],
  address: [
    "Address",
    "Patient Address",
    "Street Address",
    "Address 1",
    "Billing Address Address 1",
    "Delivery Address Address 1",
  ],
  city: [
    "City",
    "Patient City",
    "Billing Address City",
    "Delivery Address City",
  ],
  state: [
    "State",
    "Patient State",
    "Billing Address State",
    "Delivery Address State",
  ],
  zip: [
    "Zip",
    "ZIP",
    "Postal Code",
    "Zip Code",
    "Billing Address Postal Code",
    "Delivery Address Postal Code",
  ],

  primaryDoctor: [
    "Primary Doctor",
    "Primary Doctor Name",
    "PrimaryDoctor",
    "PrimaryDocName",
    "Primary Provider",
    "Primary Physician",
  ],
  orderingDoctor: [
    "Ordering Doctor",
    "Ordering Doctor Name",
    "OrderingDoctor",
    "OrderingDocName",
    "Ordering Provider",
    "Ordering Physician",
  ],
  referralName: ["Referral Name", "Referral", "Referring Provider", "Referring Doctor"],
  referralType: ["Referral Type", "ReferralType"],

  insuranceName: [
    "Insurance",
    "Primary Insurance",
    "Primary Insurance (Active only) Primary Name",
    "Insurance Name",
    "Insurance Provider",
    "Insurance_Provider",
    "Payer",
    "Payer Name",
    "Payer_Name",
    "PrimaryInsuranceName",
    "Primary_Insurance_Name",
    "Payor",
    "Payor Name",
    "Payor_Name",
  ],
  hospiceFlag: [
    "Hospice",
    "Is Hospice",
    "IsHospice",
    "Patient Is Hospice",
    "PatientIsHospice",
    "Hospice Patient",
  ],
  customerType: [
    "Patient Customer Type",
    "Customer Type",
    "PatientCustomerType",
  ],
  facility: [
    "Patient Facility",
    "Facility",
    "Facility Name",
    "PatientFacility",
  ],
  nursingAgency: [
    "Patient Nursing Agency",
    "Nursing Agency",
    "Hospice Provider",
    "PatientNursingAgency",
  ],
  emergencyContactRelationship: ["Emergency Contact Relationship"],
  emergencyContactLastName: ["Emergency Contact Last Name"],
  emergencyContactFirstName: ["Emergency Contact First Name"],
  emergencyContactPhone: ["Emergency Contact Phone"],
  responsiblePartyRelationship: ["Responsible Party Relationship"],
  responsiblePartyLastName: ["Responsible Party Last Name"],
  responsiblePartyFirstName: ["Responsible Party First Name"],
  responsiblePartyAddress1: ["Responsible Party Address 1"],
  responsiblePartyPhone: ["Responsible Party Phone"],
  primaryInsuranceName: [
    "Primary Insurance (Active only) Primary Name",
    "Primary Insurance",
    "PrimaryInsuranceName",
  ],
  primaryInsurancePolicyNumber: [
    "Primary Insurance (Active only) Policy #",
    "Primary Insurance Policy #",
    "Primary Policy #",
    "Primary Policy Number",
  ],
  primaryInsuranceGroupNumber: [
    "Primary Insurance (Active only) Group #",
    "Primary Insurance Group #",
    "Primary Group #",
    "Primary Group Number",
  ],
  secondaryInsuranceName: [
    "Secondary Insurance  (Active only) Secondary Name",
    "Secondary Insurance (Active only) Secondary Name",
    "Secondary Insurance",
    "SecondaryInsuranceName",
  ],
  secondaryInsurancePolicyNumber: [
    "Secondary Insurance  (Active only) Policy #",
    "Secondary Insurance (Active only) Policy #",
    "Secondary Insurance Policy #",
    "Secondary Policy #",
    "Secondary Policy Number",
  ],
  secondaryInsuranceGroupNumber: [
    "Secondary Insurance  (Active only) Group #",
    "Secondary Insurance (Active only) Group #",
    "Secondary Insurance Group #",
    "Secondary Group #",
    "Secondary Group Number",
  ],
} as const;
