var fs = require("fs");
var f = "functions/src/inventory/movementService.ts";
var c = fs.readFileSync(f, "utf8");
var needle = "Serialized assets must be available before retail sale.";
var idx = c.indexOf(needle);
if (idx === -1) { console.log("NOT FOUND"); process.exit(1); }
var after = idx + needle.length;
var close1 = c.indexOf("}", after);
var close2 = c.indexOf("}", close1 + 1);
var block = [];
block.push("");
block.push("  if (");
block.push('    movementType === "order_allocation" &&');
block.push("    serialized &&");
block.push("    (");
block.push("      onRentBefore > 0 ||");
block.push("      onTruckBefore > 0 ||");
block.push("      committedBefore > 0 ||");
block.push('      ["rental_out", "assigned", "checked_out", "inactive", "discontinued"].includes(status) ||');
block.push('      text(inventory.lifecycleStatus) === "retired" ||');
block.push('      text(inventory.patientKey) !== "" ||');
block.push('      text(inventory.assignedTo) !== "" ||');
block.push('      text(inventory.rentalId) !== ""');
block.push("    )");
block.push("  ) {");
block.push('    throw new HttpsError("failed-precondition", "Serialized inventory is not available for order allocation.");');
block.push("  }");
var insertText = block.join("\n") + "\n";
var nc = c.slice(0, close2) + insertText + c.slice(close2);
fs.writeFileSync(f, nc);
console.log("SUCCESS");